// Code generated by the Lingua Franca compiler from:
// file://Users/naichenzhao/Desktop/EECS149-Project/lfc_controller/src/Main.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/naichenzhao/Desktop/EECS149-Project/lfc_controller/src-gen/Main"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
#include "_qdec.h"
#include "_dac.h"
#include "_pid_controller.h"
#include "_main_main.h"
typedef enum {
    main_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[main_main],main_main,_lf_number_of_workers,2,4,0,0,5,1,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _main_main_main_self_t* main_main_self[1];
    SUPPRESS_UNUSED_WARNING(main_main_self);
    _qdec_self_t* main_qdec_self[1];
    SUPPRESS_UNUSED_WARNING(main_qdec_self);
    _dac_self_t* main_dac_self[1];
    SUPPRESS_UNUSED_WARNING(main_dac_self);
    _pid_controller_self_t* main_pid_controller_self[1];
    SUPPRESS_UNUSED_WARNING(main_pid_controller_self);
    // ***** Start initializing Main of class Main
    main_main_self[0] = new__main_main();
    main_main_self[0]->base.environment = &envs[main_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[main_main].startup_reactions[startup_reaction_count[main_main]++] = &main_main_self[0]->_lf__reaction_0;
    envs[main_main].startup_reactions[startup_reaction_count[main_main]++] = &main_main_self[0]->_lf__reaction_1;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static int _initial = 10000;
        main_main_self[0]->pos = _initial;
    } // End scoping.
    { // For scoping
        static int32_t _initial = 0;
        main_main_self[0]->encoder_count = _initial;
    } // End scoping.
    { // For scoping
        static int _initial = 1;
        main_main_self[0]->sign = _initial;
    } // End scoping.
    // Initiaizing timer Main.change_pos.
    main_main_self[0]->_lf__change_pos.offset = MSEC(0);
    main_main_self[0]->_lf__change_pos.period = MSEC(3000);
    // Associate timer with the environment of its parent
    envs[main_main].timer_triggers[timer_triggers_count[main_main]++] = &main_main_self[0]->_lf__change_pos;
    main_main_self[0]->_lf__change_pos.mode = NULL;
    // Initiaizing timer Main.update.
    main_main_self[0]->_lf__update.offset = MSEC(0);
    main_main_self[0]->_lf__update.period = MSEC(10);
    // Associate timer with the environment of its parent
    envs[main_main].timer_triggers[timer_triggers_count[main_main]++] = &main_main_self[0]->_lf__update;
    main_main_self[0]->_lf__update.mode = NULL;
    // Initializing action Main.force_triggered
    main_main_self[0]->_lf__force_triggered.offset = 0;
    main_main_self[0]->_lf__force_triggered.period = -1;
    main_main_self[0]->_lf__force_triggered.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(main_main_self[0]->_lf__force_triggered),
    0);
    main_main_self[0]->_lf__force_triggered.status = absent;
    main_main_self[0]->_lf__reaction_0.deadline = NEVER;
    main_main_self[0]->_lf__reaction_1.deadline = NEVER;
    main_main_self[0]->_lf__reaction_2.deadline = NEVER;
    main_main_self[0]->_lf__reaction_3.deadline = NEVER;
    main_main_self[0]->_lf__reaction_4.deadline = NEVER;
    main_main_self[0]->_lf__reaction_5.deadline = NEVER;
    main_main_self[0]->_lf__reaction_6.deadline = NEVER;
    main_main_self[0]->_lf__reaction_7.deadline = NEVER;
    // Register for transition handling
    envs[main_main].modes->modal_reactor_states[modal_reactor_count[main_main]++] = &((self_base_t*)main_main_self[0])->_lf__mode_state;
    {
        _main_main_main_self_t *self = main_main_self[0];
        // ***** Start initializing Main.qdec of class QDEC
        main_qdec_self[0] = new__qdec();
        main_qdec_self[0]->base.environment = &envs[main_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        main_qdec_self[0]->_lf_read_width = -2;
        // width of -2 indicates that it is not a multiport.
        main_qdec_self[0]->_lf_trigger_width = -2;
        envs[main_main].startup_reactions[startup_reaction_count[main_main]++] = &main_qdec_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        main_qdec_self[0]->_lf__reaction_0.deadline = NEVER;
        main_qdec_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Main.qdec
    }
    {
        _main_main_main_self_t *self = main_main_self[0];
        // ***** Start initializing Main.dac of class DAC
        main_dac_self[0] = new__dac();
        main_dac_self[0]->base.environment = &envs[main_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        main_dac_self[0]->_lf_setvalue_width = -2;
        envs[main_main].startup_reactions[startup_reaction_count[main_main]++] = &main_dac_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        main_dac_self[0]->_lf__reaction_0.deadline = NEVER;
        main_dac_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Main.dac
    }
    {
        _main_main_main_self_t *self = main_main_self[0];
        // ***** Start initializing Main.pid_controller of class PID_Controller
        main_pid_controller_self[0] = new__pid_controller();
        main_pid_controller_self[0]->base.environment = &envs[main_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        main_pid_controller_self[0]->Kp = 0.8;
        main_pid_controller_self[0]->Ki = 0.1;
        main_pid_controller_self[0]->Kd = 0.1;
        // width of -2 indicates that it is not a multiport.
        main_pid_controller_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        main_pid_controller_self[0]->_lf_current_pos_width = -2;
        // width of -2 indicates that it is not a multiport.
        main_pid_controller_self[0]->_lf_target_pos_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        { // For scoping
            static int32_t _initial = 0;
            main_pid_controller_self[0]->last_pos = _initial;
        } // End scoping.
        main_pid_controller_self[0]->prev_time = 0;
        { // For scoping
            static float _initial = 0.9;
            main_pid_controller_self[0]->Kw = _initial;
        } // End scoping.
        { // For scoping
            static float _initial = 0;
            main_pid_controller_self[0]->error_i = _initial;
        } // End scoping.
    
        main_pid_controller_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing Main.pid_controller
    }
    //***** End initializing Main
    // **** Start deferred initialize for Main
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of Main.
        main_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of Main.
        main_main_self[0]->_lf__reaction_1.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 1 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of Main.
        main_main_self[0]->_lf__reaction_2.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 2 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of Main.
        main_main_self[0]->_lf__reaction_3.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 3 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_5 of Main.
        main_main_self[0]->_lf__reaction_4.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 4 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_6 of Main.
        main_main_self[0]->_lf__reaction_5.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        main_main_self[0]->_lf__reaction_5.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &main_main_self[0]->base.allocations);
        main_main_self[0]->_lf__reaction_5.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &main_main_self[0]->base.allocations);
        main_main_self[0]->_lf__reaction_5.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &main_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                main_main_self[0]->_lf__reaction_5.output_produced[count++] = &main_main_self[0]->_lf_pid_controller.target_pos.is_present;
            }
        }
        
        // ** End initialization for reaction 5 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_7 of Main.
        main_main_self[0]->_lf__reaction_6.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        main_main_self[0]->_lf__reaction_6.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &main_main_self[0]->base.allocations);
        main_main_self[0]->_lf__reaction_6.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &main_main_self[0]->base.allocations);
        main_main_self[0]->_lf__reaction_6.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &main_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                main_main_self[0]->_lf__reaction_6.output_produced[count++] = &main_main_self[0]->_lf_qdec.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 6 of Main
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_8 of Main.
        main_main_self[0]->_lf__reaction_7.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 7 of Main
    
        // **** Start deferred initialize for Main.qdec
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Main.qdec.
            main_qdec_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Main.qdec
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Main.qdec.
            main_qdec_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            main_qdec_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &main_qdec_self[0]->base.allocations);
            main_qdec_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &main_qdec_self[0]->base.allocations);
            main_qdec_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &main_qdec_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    main_qdec_self[0]->_lf__reaction_1.output_produced[count++] = &main_qdec_self[0]->_lf_read.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of Main.qdec
        
        }
        // **** End of deferred initialize for Main.qdec
        // **** Start deferred initialize for Main.dac
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Main.dac.
            main_dac_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of Main.dac
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of Main.dac.
            main_dac_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of Main.dac
        
        }
        // **** End of deferred initialize for Main.dac
        // **** Start deferred initialize for Main.pid_controller
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Main.pid_controller.
            main_pid_controller_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            main_pid_controller_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &main_pid_controller_self[0]->base.allocations);
            main_pid_controller_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &main_pid_controller_self[0]->base.allocations);
            main_pid_controller_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &main_pid_controller_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    main_pid_controller_self[0]->_lf__reaction_0.output_produced[count++] = &main_pid_controller_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Main.pid_controller
        
        }
        // **** End of deferred initialize for Main.pid_controller
    }
    // **** End of deferred initialize for Main
    // **** Start non-nested deferred initialize for Main
    {
        // Set number of destination reactors for port pid_controller.target_pos.
        // Iterate over range Main.pid_controller.target_pos(0,1)->[Main.pid_controller.target_pos(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_main_self[src_runtime]->_lf_pid_controller.target_pos._base.num_destinations = 1;
            main_main_self[src_runtime]->_lf_pid_controller.target_pos._base.source_reactor = (self_base_t*)main_main_self[src_runtime];
        }
        // Set number of destination reactors for port qdec.trigger.
        // Iterate over range Main.qdec.trigger(0,1)->[Main.qdec.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_main_self[src_runtime]->_lf_qdec.trigger._base.num_destinations = 1;
            main_main_self[src_runtime]->_lf_qdec.trigger._base.source_reactor = (self_base_t*)main_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range Main.pid_controller.target_pos(0,1)->[Main.pid_controller.target_pos(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 5 of Main triggers 1 downstream reactions
                // through port Main.pid_controller.target_pos.
                main_main_self[src_runtime]->_lf__reaction_5.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 5 of Main, allocate an
                // array of trigger pointers for downstream reactions through port Main.pid_controller.target_pos
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &main_main_self[src_runtime]->base.allocations); 
                main_main_self[src_runtime]->_lf__reaction_5.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges Main.pid_controller.target_pos(0,1)->[Main.pid_controller.target_pos(0,1)] and Main.pid_controller.target_pos(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range Main.pid_controller.target_pos(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port Main.pid_controller.target_pos's trigger struct.
                    main_main_self[src_runtime]->_lf__reaction_5.triggers[triggers_index[src_runtime] + src_channel][0] = &main_pid_controller_self[dst_runtime]->_lf__target_pos;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range Main.qdec.trigger(0,1)->[Main.qdec.trigger(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 6 of Main triggers 1 downstream reactions
                // through port Main.qdec.trigger.
                main_main_self[src_runtime]->_lf__reaction_6.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 6 of Main, allocate an
                // array of trigger pointers for downstream reactions through port Main.qdec.trigger
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &main_main_self[src_runtime]->base.allocations); 
                main_main_self[src_runtime]->_lf__reaction_6.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges Main.qdec.trigger(0,1)->[Main.qdec.trigger(0,1)] and Main.qdec.trigger(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range Main.qdec.trigger(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port Main.qdec.trigger's trigger struct.
                    main_main_self[src_runtime]->_lf__reaction_6.triggers[triggers_index[src_runtime] + src_channel][0] = &main_qdec_self[dst_runtime]->_lf__trigger;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for Main.qdec
        {
        
            // For reference counting, set num_destinations for port Main.qdec.read.
            // Iterate over range Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                main_qdec_self[src_runtime]->_lf_read._base.num_destinations = 2;
                main_qdec_self[src_runtime]->_lf_read._base.source_reactor = (self_base_t*)main_qdec_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of Main.qdec triggers 2 downstream reactions
                    // through port Main.qdec.read.
                    main_qdec_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 2;
                    // For reaction 1 of Main.qdec, allocate an
                    // array of trigger pointers for downstream reactions through port Main.qdec.read
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            2, sizeof(trigger_t*),
                            &main_qdec_self[src_runtime]->base.allocations); 
                    main_qdec_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)] and Main.qdec.read(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Main.qdec.read(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port Main.qdec.read has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        main_qdec_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &main_main_self[dst_runtime]->_lf_qdec.read_trigger;
                    }
                }
                // Iterate over ranges Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)] and Main.pid_controller.current_pos(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Main.pid_controller.current_pos(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Main.pid_controller.current_pos's trigger struct.
                        main_qdec_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][1] = &main_pid_controller_self[dst_runtime]->_lf__current_pos;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Main.qdec
        // **** Start non-nested deferred initialize for Main.dac
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for Main.dac
        // **** Start non-nested deferred initialize for Main.pid_controller
        {
        
            // For reference counting, set num_destinations for port Main.pid_controller.out.
            // Iterate over range Main.pid_controller.out(0,1)->[Main.dac.setvalue(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                main_pid_controller_self[src_runtime]->_lf_out._base.num_destinations = 1;
                main_pid_controller_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)main_pid_controller_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range Main.pid_controller.out(0,1)->[Main.dac.setvalue(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of Main.pid_controller triggers 1 downstream reactions
                    // through port Main.pid_controller.out.
                    main_pid_controller_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of Main.pid_controller, allocate an
                    // array of trigger pointers for downstream reactions through port Main.pid_controller.out
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &main_pid_controller_self[src_runtime]->base.allocations); 
                    main_pid_controller_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges Main.pid_controller.out(0,1)->[Main.dac.setvalue(0,1)] and Main.dac.setvalue(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range Main.dac.setvalue(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port Main.dac.setvalue's trigger struct.
                        main_pid_controller_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &main_dac_self[dst_runtime]->_lf__setvalue;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for Main.pid_controller
    }
    // **** End of non-nested deferred initialize for Main
    // Connect inputs and outputs for reactor Main.
    // Connect inputs and outputs for reactor Main.qdec.
    // Connect Main.qdec.trigger(0,1)->[Main.qdec.trigger(0,1)] to port Main.qdec.trigger(0,1)
    // Iterate over ranges Main.qdec.trigger(0,1)->[Main.qdec.trigger(0,1)] and Main.qdec.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.qdec.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_qdec_self[dst_runtime]->_lf_trigger = (_qdec_trigger_t*)&main_main_self[src_runtime]->_lf_qdec.trigger;
        }
    }
    // Connect Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)] to port Main.qdec.read(0,1)
    // Iterate over ranges Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)] and Main.qdec.read(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.qdec.read(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_main_self[dst_runtime]->_lf_qdec.read = (_qdec_read_t*)&main_qdec_self[src_runtime]->_lf_read;
        }
    }
    // Connect Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)] to port Main.pid_controller.current_pos(0,1)
    // Iterate over ranges Main.qdec.read(0,1)->[Main.qdec.read(0,1), Main.pid_controller.current_pos(0,1)] and Main.pid_controller.current_pos(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.pid_controller.current_pos(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_pid_controller_self[dst_runtime]->_lf_current_pos = (_pid_controller_current_pos_t*)&main_qdec_self[src_runtime]->_lf_read;
        }
    }
    // Connect inputs and outputs for reactor Main.dac.
    // Connect inputs and outputs for reactor Main.pid_controller.
    // Connect Main.pid_controller.target_pos(0,1)->[Main.pid_controller.target_pos(0,1)] to port Main.pid_controller.target_pos(0,1)
    // Iterate over ranges Main.pid_controller.target_pos(0,1)->[Main.pid_controller.target_pos(0,1)] and Main.pid_controller.target_pos(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.pid_controller.target_pos(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_pid_controller_self[dst_runtime]->_lf_target_pos = (_pid_controller_target_pos_t*)&main_main_self[src_runtime]->_lf_pid_controller.target_pos;
        }
    }
    // Connect Main.pid_controller.out(0,1)->[Main.dac.setvalue(0,1)] to port Main.dac.setvalue(0,1)
    // Iterate over ranges Main.pid_controller.out(0,1)->[Main.dac.setvalue(0,1)] and Main.dac.setvalue(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Main.dac.setvalue(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            main_dac_self[dst_runtime]->_lf_setvalue = (_dac_setvalue_t*)&main_pid_controller_self[src_runtime]->_lf_out;
        }
    }
    {
    }
    {
    }
    {
    }
    // Add port Main.pid_controller.target_pos to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[main_main].is_present_fields[0 + count] = &main_main_self[0]->_lf_pid_controller.target_pos.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[main_main]._lf_intended_tag_fields[0 + count] = &main_main_self[0]->_lf_pid_controller.target_pos.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port Main.qdec.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[main_main].is_present_fields[1 + count] = &main_main_self[0]->_lf_qdec.trigger.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[main_main]._lf_intended_tag_fields[1 + count] = &main_main_self[0]->_lf_qdec.trigger.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action Main.force_triggered to array of is_present fields.
        envs[main_main].is_present_fields[2] 
                = &main_main_self[0]->_lf_force_triggered.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Main.force_triggered to array of intended_tag fields.
        envs[main_main]._lf_intended_tag_fields[2] 
                = &main_main_self[0]->_lf_force_triggered.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Main.qdec.read to array of is_present fields.
            envs[main_main].is_present_fields[3 + count] = &main_qdec_self[0]->_lf_read.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Main.qdec.read to array of intended_tag fields.
            envs[main_main]._lf_intended_tag_fields[3 + count] = &main_qdec_self[0]->_lf_read.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Main.pid_controller.out to array of is_present fields.
            envs[main_main].is_present_fields[4 + count] = &main_pid_controller_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Main.pid_controller.out to array of intended_tag fields.
            envs[main_main]._lf_intended_tag_fields[4 + count] = &main_pid_controller_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance Main
    {
        main_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        main_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        main_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        main_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0003LL;
        main_main_self[0]->_lf__reaction_4.chain_id = 1;
        // index is the OR of level 4 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_4.index = 0xffffffffffff0004LL;
        main_main_self[0]->_lf__reaction_5.chain_id = 1;
        // index is the OR of level 5 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_5.index = 0xffffffffffff0005LL;
        main_main_self[0]->_lf__reaction_6.chain_id = 1;
        // index is the OR of level 6 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_6.index = 0xffffffffffff0006LL;
        main_main_self[0]->_lf__reaction_7.chain_id = 1;
        // index is the OR of level 8 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        main_main_self[0]->_lf__reaction_7.index = 0xffffffffffff0008LL;
    
        // Set reaction priorities for ReactorInstance Main.qdec
        {
            main_qdec_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_qdec_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            main_qdec_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 7 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_qdec_self[0]->_lf__reaction_1.index = 0xffffffffffff0007LL;
        }
    
    
        // Set reaction priorities for ReactorInstance Main.dac
        {
            main_dac_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_dac_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            main_dac_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 9 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_dac_self[0]->_lf__reaction_1.index = 0xffffffffffff0009LL;
        }
    
    
        // Set reaction priorities for ReactorInstance Main.pid_controller
        {
            main_pid_controller_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 8 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            main_pid_controller_self[0]->_lf__reaction_0.index = 0xffffffffffff0008LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
